item {
  id: 1
  name: 'r1'
  display_name: 'JingZhiShiRu'
}

item {
  id: 2
  name: 'r2'
  display_name: 'JingZhiJiDongCheShiRu'
}

item {
  id: 3
  name: 'r3'
  display_name: 'JingZhiDiaoTou'
}

item {
  id: 4
  name: 'r4'
  display_name: 'JingZhiChaoChe'
}

item {
  id: 5
  name: 'r5'
  display_name: 'JingZhiTingChe'
}

item {
  id: 6
  name: 'r6'
  display_name: 'XianZhiSuDu'
}

item {
  id: 7
  name: 'b1'
  display_name: 'HuanDaoXingShi'
}

item {
  id: 8
  name: 'b2'
  display_name: 'JiDongCheXingShi'
}

item {
  id: 9
  name: 'b3'
  display_name: 'JiDongCheCheDao'
}

item {
  id: 10
  name: 'b4'
  display_name: 'TingCheWei'
}

item {
  id: 11
  name: 'y1'
  display_name: 'ShiGong'
}

item {
  id: 12
  name: 'y2'
  display_name: 'XiangZuoXingShi'
}

item {
  id: 13
  name: 'y3'
  display_name: 'XiangYouXingShi'
}

item {
  id: 14
  name: 'y4'
  display_name: 'ETCShouFeiZhan'
}

item {
  id: 15
  name: 'rl'
  display_name: 'YuanXingHongDeng'
}

item {
  id: 16
  name: 'yl'
  display_name: 'YuanXingHuangDeng'
}

item {
  id: 17
  name: 'gl'
  display_name: 'YuanXingLvDeng'
}

item {
  id: 18
  name: 'rla'
  display_name: 'ZuoZhuanJianTouHongDeng'
}

item {
  id: 19
  name: 'yla'
  display_name: 'ZuoZhuanJianTouHuangDeng'
}

item {
  id: 20
  name: 'gla'
  display_name: 'ZuoZhuanJianTouLvDeng'
}

item {
  id: 21
  name: 'rfa'
  display_name: 'ZhiXingJianTouHongDeng'
}

item {
  id: 22
  name: 'yfa'
  display_name: 'ZhiXingJianTouHuangDeng'
}

item {
  id: 23
  name: 'gfa'
  display_name: 'ZhiXingJianTouLvDeng'
}

item {
  id: 24
  name: 'rra'
  display_name: 'YouZhuanJianTouHongDeng'
}

item {
  id: 25
  name: 'yra'
  display_name: 'YouZhuanJianTouHuangDeng'
}

item {
  id: 26
  name: 'gra'
  display_name: 'YouZhuanJianTouLvDeng'
}